In [7]:
import pandas as pd

In [8]:
df1 = pd.read_csv("https://media.githubusercontent.com/media/kamilyassis/pln/refs/heads/main/datasets/conexao-labels-full-4.1nano-p2.csv", sep="|")
print(df1.shape)
df1['source'] = 'conexao-labels-full-4.1nano-p2'
df1.head()

(12287, 3)

,sentence,label,justification,source
0,E certamente com o risco de ser injusto com al...,Loaded_Language,The sentence uses emotionally charged words li...,conexao-labels-full-4.1nano-p2
1,"Queda de 27,5% em relação ao mesmo período do ...",No_Label,The sentences are factual reports and do not c...,conexao-labels-full-4.1nano-p2
2,"A seguir, são sugeridas algumas medidas de com...",No_Label,The sentence is informational and describes me...,conexao-labels-full-4.1nano-p2
3,Cito onze aqui:\n– PL 6944/2017: impede a limi...,No_Label,"The sentence is informational, listing legisla...",conexao-labels-full-4.1nano-p2
4,"Um ex-presidente, dos mais populares e populis...",Loaded_Language,The sentence uses emotionally charged words li...,conexao-labels-full-4.1nano-p2

In [9]:
df2 = pd.read_csv("https://media.githubusercontent.com/media/kamilyassis/pln/refs/heads/main/datasets/g1-labels-full-4.1nano-p2.csv")
print(df2.shape)
df2['source'] = 'g1-labels-full-4.1nano-p2'
df2.head()

(3668, 3)

,sentence,label,justification,source
0,O vídeo foi gravado no cemitério de Annotto Ba...,No_Label,"The sentence is purely informational, describi...",g1-labels-full-4.1nano-p2
1,OFato ou Fakepesquisou pelo cemitério de Annot...,No_Label,The sentence provides factual information abou...,g1-labels-full-4.1nano-p2
2,Mas isso não é verdade.OFato ou Fakeenviou o m...,No_Label,The sentence primarily relays factual informat...,g1-labels-full-4.1nano-p2
3,"Segundo o ex-ministro do TSE Carlos Horbach, r...",No_Label,The sentence is a detailed explanation of a le...,g1-labels-full-4.1nano-p2
4,"Não há, no texto do ECA Digital, qualquer menç...",No_Label,The sentence provides an informational clarifi...,g1-labels-full-4.1nano-p2

In [10]:
df3 = pd.read_csv("https://media.githubusercontent.com/media/kamilyassis/pln/refs/heads/main/datasets/g1_faketrue_treated.csv", sep="|")
print(df3.shape)
df3['source'] = 'g1_faketrue_treated'
df3.head()

(1747, 3)

,sentence,label,justification,source
0,carnaval em olinda. arrastão monstro. fazuele ...,Name_Calling-Labeling,O texto utiliza a rotulação ao chamar Lula de ...,g1_faketrue_treated
1,carro alegórico da escola de samba grande rio...,Appeal_to_Fear-Prejudice,O texto utiliza o medo ao mencionar que há 'ca...,g1_faketrue_treated
2,cantor léo apoiando atos antidemocráticos. alg...,Name_Calling-Labeling,O texto menciona 'cantor léo apoiando atos ant...,g1_faketrue_treated
3,versão 1 ore muito pela cantora anitta! ela es...,Appeal_to_Fear-Prejudice,O texto utiliza apelo ao medo ao descrever a g...,g1_faketrue_treated
4,globo já gravou o vídeo de fim de ano com lula...,Loaded_Language,"O texto utiliza linguagens carregadas, como ""v...",g1_faketrue_treated

In [11]:
df_final = pd.concat([df1, df2, df3], ignore_index=True)
print(df_final.shape)
df_final.head()

(17702, 4)

,sentence,label,justification,source
0,E certamente com o risco de ser injusto com al...,Loaded_Language,The sentence uses emotionally charged words li...,conexao-labels-full-4.1nano-p2
1,"Queda de 27,5% em relação ao mesmo período do ...",No_Label,The sentences are factual reports and do not c...,conexao-labels-full-4.1nano-p2
2,"A seguir, são sugeridas algumas medidas de com...",No_Label,The sentence is informational and describes me...,conexao-labels-full-4.1nano-p2
3,Cito onze aqui:\n– PL 6944/2017: impede a limi...,No_Label,"The sentence is informational, listing legisla...",conexao-labels-full-4.1nano-p2
4,"Um ex-presidente, dos mais populares e populis...",Loaded_Language,The sentence uses emotionally charged words li...,conexao-labels-full-4.1nano-p2

In [12]:
save = True
if save:
    df_final.to_csv("../datasets/combined_dataset.csv", index=False)