In [1]:
import pandas as pd

In [2]:
df = pd.read_json('in/articles.jsonl', lines=True)
print(df.shape)
df.head()

(2922, 9)

,title,subtitle,from_publication,date_publication,json_ld,content,url,html_path,scraped_at
0,É #FATO: Cemitério na Jamaica tem 'totens' com...,Vídeo viral foi gravado no cemitério de Annott...,PorRedação g1,23/03/2026 15h51Atualizadohá 2 dias,None,"[{'tag': 'figcaption', 'text': '1 de 4 É #FATO...",https://g1.globo.com/fato-ou-fake/noticia/2026...,data/html_cache/000000_article.html,2026-03-25 21:05:34.287914
1,É #FAKE que TSE proibiu Bolsonaro de baixar pr...,"Ao Fato ou Fake, TSE disse: 'conteúdo é falso'...",PorRedação g1,25/03/2026 17h42Atualizadohá uma hora,"[{'articleSection': ['G1', 'Fato ou Fake']}]","[{'tag': 'figcaption', 'text': '1 de 3 TSE não...",https://g1.globo.com/fato-ou-fake/noticia/2026...,data/html_cache/000001_article.html,2026-03-25 21:05:35.186873
2,É #FAKE que 'Lei Felca' causará bloqueio de iP...,ECA Digital não prevê bloqueio de aparelhos ou...,"Por O Globo, Luiz Eduardo de Castro",25/03/2026 09h07Atualizadohá 11 horas,None,"[{'tag': 'figcaption', 'text': '1 de 3 É #FAKE...",https://g1.globo.com/fato-ou-fake/noticia/2026...,data/html_cache/000002_article.html,2026-03-25 21:05:35.566225
3,É #FAKE foto de posto com litro de gasolina co...,Posts enganosos utilizam foto com valores alte...,PorRedação g1,24/03/2026 15h47Atualizadohá um dia,None,"[{'tag': 'figcaption', 'text': '1 de 6 É #FAKE...",https://g1.globo.com/fato-ou-fake/noticia/2026...,data/html_cache/000003_article.html,2026-03-25 21:05:35.829453
4,É #FATO: Vídeo mostra canguru deitado recebend...,Cena foi gravada em maio de 2025 em local envo...,"PorMel Trench, g1",24/03/2026 10h01Atualizadohá 10 horas,None,"[{'tag': 'section', 'text': 'Assista também no...",https://g1.globo.com/fato-ou-fake/noticia/2026...,data/html_cache/000004_article.html,2026-03-25 21:05:36.082339

In [ ]:
from unidecode import unidecode

def extract_blockquote_and_next(url, content_list):
    results = []
    for i, item in enumerate(content_list):
        if not item.get('tag') or not item['tag'] == 'blockquote':
            continue

        # Try to find matching <p> within 2-3 elements away
        found_match = None
        for j in range(i + 1, min(i + 4, len(content_list))):  # i+1 to i+3 (2-3 elements)
            next_item = content_list[j]
            if not next_item.get('tag') or next_item['tag'] != 'p':
                continue
            
            text = next_item.get('text', '')
            unidecoded_text = unidecode(str(text)).strip().lower()
            lower_text = str(text).strip().lower()
            if (
                any(keyword in unidecoded_text for keyword in ['#fato', '#fake', '#naoebemassim'])
                and 'foto:' not in lower_text 
                and 'veja o que e #fato ou #fake sobre' not in unidecoded_text
                and
                ):
                found_match = next_item
                break
        
        # If no match within 2-3 elements, check if keywords are in any <p> in the document
        if found_match is None:
            for content_item in content_list:
                if not content_item.get('tag') or content_item['tag'] != 'p':
                    continue
                text = content_item.get('text', '')
                unidecoded_text = unidecode(str(text)).strip().lower()
                lower_text = str(text).strip().lower()
                if any(keyword in unidecoded_text for keyword in ['#fato', '#fake', '#naoebemassim']) and 'foto:' not in lower_text and 'veja o que e #fato ou #fake sobre' not in unidecoded_text:
                    found_match = content_item
                    break
        
        # Only append if we found a matching <p> tag
        if found_match is not None:
            results.append({
                'blockquote': item,
                'next_item': found_match,
                'url': url
            })
    
    return results

extracted = df[['url', 'content']].apply(lambda row: extract_blockquote_and_next(row['url'], row['content']), axis=1)
extracted_df = pd.DataFrame([item for sublist in extracted for item in sublist])

In [111]:
from unidecode import unidecode

def extract_blockquote_and_next(url, content_list):
    results = []
    for i, item in enumerate(content_list):
        if not item.get('tag') or not item['tag'] == 'blockquote':
            continue

        found_p = None
        found_p_text = None
        found_p_index = None
        
        # Try to find <p> within 2-3 elements away
        for j in range(i + 1, min(i + 4, len(content_list))):
            next_item = content_list[j]
            if next_item.get('tag') != 'p':
                continue
            
            text = next_item.get('text', '')
            unidecoded_text = unidecode(str(text)).strip().lower()
            lower_text = str(text).strip().lower()
            if (
                any(keyword in unidecoded_text for keyword in ['#fato', '#fake', '#naoebemassim'])
                and 'foto:' not in lower_text 
                and 'veja o que e #fato ou #fake sobre' not in unidecoded_text
            ):
                found_p = next_item
                found_p_text = text
                found_p_index = j
                break
        
        # If we found a <p>, check for <ul> in the next 1-3 elements
        if found_p is not None:
            final_text = found_p_text
            
            for k in range(found_p_index + 1, min(found_p_index + 4, len(content_list))):
                ul_item = content_list[k]
                if ul_item.get('tag') == 'ul':
                    li_texts = []
                    
                    # Check if <li> are children of <ul>
                    if 'children' in ul_item:
                        for li in ul_item.get('children', []):
                            if li.get('tag') == 'li':
                                li_texts.append(li.get('text', '').strip())
                    else:
                        # Otherwise, look for <li> items following the <ul>
                        for m in range(k + 1, len(content_list)):
                            li_item = content_list[m]
                            if li_item.get('tag') == 'li':
                                li_texts.append(li_item.get('text', '').strip())
                            else:
                                break  # Stop at first non-<li>
                    
                    if li_texts:
                        final_text = found_p_text + ' ' + ';'.join(li_texts)
                    break
            
            results.append({
                'blockquote': item,
                'next_item': found_p,
                'next_item_text': final_text,
                'url': url
            })
            continue
        
        # If no <p> match within 2-3 elements, check anywhere in document
        for content_item in content_list:
            if not content_item.get('tag') or content_item['tag'] != 'p':
                continue
            text = content_item.get('text', '')
            unidecoded_text = unidecode(str(text)).strip().lower()
            lower_text = str(text).strip().lower()
            if any(keyword in unidecoded_text for keyword in ['#fato', '#fake', '#naoebemassim']) and 'foto:' not in lower_text and 'veja o que e #fato ou #fake sobre' not in unidecoded_text:
                results.append({
                    'blockquote': item,
                    'next_item': content_item,
                    'next_item_text': text,
                    'url': url
                })
                break
    
    return results

extracted = df[['url', 'content']].apply(lambda row: extract_blockquote_and_next(row['url'], row['content']), axis=1)
extracted_df = pd.DataFrame([item for sublist in extracted for item in sublist])

In [112]:
print(extracted_df.shape)

(3751, 4)

In [113]:
# make the url appear completely on head view
pd.set_option('display.max_colwidth', None)

extracted_df['blockquote_text'] = extracted_df['blockquote'].apply(lambda x: x.get('text', ''))
extracted_df['next_item_text'] = extracted_df['next_item'].apply(lambda x: x.get('text', ''))

In [114]:
# keep only rows in which blockquote_text starts with '"'
#extracted_df = extracted_df[extracted_df['next_item_text'].str.contains('declaração|declaracao|declarou|declarou que|declarou ser|declarou ser que|afirmou|afirmacao|afirmação|afirmou que|afirmou ser|afirmou ser que', case=False, na=False)]
#print(extracted_df.shape)

In [115]:
extracted_df[['blockquote_text', 'next_item_text', 'url']].sample(10)

,blockquote_text,next_item_text,url
3688,"""O ministro Tarcísio e o presidente Bolsonaro sinalizaram esta vontade de empenhar este recurso da multa da Vale na implementação da linha 2 do metrô. (...) Não é uma coisa que vai acontecer se o Bruno Engler for prefeito. É uma coisa que o governo federal vai fazer, independente de quem ganhar. O prefeito eleito, se ele tiver disponibilidade para fazer este empreendimento em parceria com União, acredito que vai sair” (em entrevista ao jornal ‘Hoje em Dia’, em 6/10)","A declaração é #FAKE. Veja o porquê:Em um momento, o candidato cita um valor e diz que ele não foi enviado para a cidade. Em outro momento, reforça que a cidade não recebeu nenhuma ajuda. Não é verdade. De acordo com o Ministério do Desenvolvimento Regional, foram destinados R$ 10,8 milhões para ações de Defesa Civil em Belo Horizonte.",https://g1.globo.com/fato-ou-fake/noticia/2020/10/09/veja-o-que-e-fato-ou-fake-nas-declaracoes-dos-candidatos-a-prefeitura-de-belo-horizonte-na-2a-semana-de-campanha.ghtml
2618,"“Niterói, nos últimos oito anos da minha gestão, conquistou pela CGU, que é um órgão independente do governo federal, e também pelo Ministério Público Federal, o primeiro lugar em transparência na administração municipal dentre os 92 municípios do estado.”","A declaração é #FATO. Veja por quê:A Escala Brasil, levantamento da Controladoria Geral da União (CGU), avaliou 665 municípios no país, em 2020, e considerou Niterói a 1ª cidade no ranking no estado, ao lado das cidades de Mesquita, na Baixada Fluminense, e São Pedro da Aldeia, na Região dos Lagos.",https://g1.globo.com/rj/rio-de-janeiro/eleicoes/2022/noticia/2022/09/12/veja-o-que-e-fato-ou-fake-na-entrevista-de-rodrigo-neves-ao-rj1.ghtml
709,"""A Receita Federal não tem poder para criar impostos. Isso é uma atribuição exclusiva do Poder Legislativo – ou seja, só pode ser feito por meio de leis aprovadas pelo Congresso Nacional (ao nível federal), pelas Assembleias Legislativas (ao nível estadual) ou pelas Câmaras Municipais (em nível municipal). Este é outro pilar fundamental do sistema tributário brasileiro, o Princípio da Estrita Legalidade Tributária, que garante que nenhum tributo pode ser instituído ou majorado sem lei que o estabeleça"", diz Movan.","Circulam nas redes sociais publicações dizendo que aReceita Federalirá cobrar imposto de adultos que moram com os pais, a partir de 2026.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/09/25/e-fake-que-a-receita-federal-vai-cobrar-impostos-de-adultos-que-moram-com-os-pais.ghtml
2883,"""Esse governo (Jair Bolsonaro) cortou 98% da construção de casas populares para quem ganha até 1,5 salário mínimo"". (em entrevista a O Globo, em 25/08)","#NÃOÉBEMASSIM. Veja por quê:De acordo com a pesquisa Genial/Quaest (feita entre os dias 11 e 12 de agosto), os eleitores entrevistados que não apresentaram decisão clara, sem estímulo,correspondem a 36%. No entanto, segundo a última pesquisa com perguntas espontâneas do Instituto Datafolha (feita entre 16 e 18 de agosto), o número de indecisos no mês giraem torno de 22%, o que equivale a quase 1/4 dos entrevistados.",https://g1.globo.com/fato-ou-fake/eleicoes/noticia/2022/08/26/veja-o-que-e-fato-ou-fake-na-sabatina-de-simone-tebet-para-o-globo-valor-e-cbn.ghtml
1558,"""Ele [o produto] é classificado como suplemento alimentar, e suplementos não podem fazer alegações terapêuticas, como o tratamento de doenças, incluindo a disfunção erétil. De acordo com as Resoluções RDC Anvisa nº 27/2010 e nº 240/2018, suplementos alimentares estão isentos de registro na Anvisa, desde que cumpram os requisitos estabelecidos nessas normas"", explica Messina.","Circula nas redes sociais uma publicação que imita a página dog1com o título ""Revolucionário: sexóloga aprova spray de alga pra tratar disfunção erétil e ameaça quebrar indústria farmacêutica"".É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/01/08/e-fake-que-spray-de-alga-trate-ou-previna-disfuncao-eretil.ghtml
1959,"“A cidade hoje está puro esgoto naquilo que a gente chama de rio. Desde 1990 eles não conseguem limpar esse rio.""","A declaração é #FATO. Veja por quê:Segundos os dados do Observatório Brasileiro de Políticas Públicas com a População em Situação de Rua (OBPopRua), da Universidade Federal de Minas Gerais (UFMG), a cidade de São Paulo tem um total de80.369 pessoas vivendo em situação de ruaem junho deste ano. Os números representam um aumento de 24% em relação a dezembro de 2023.",https://g1.globo.com/fato-ou-fake/sao-paulo/noticia/2024/08/09/veja-o-que-e-fato-ou-fake-na-entrevista-de-pablo-marcal-para-o-assunto.ghtml
2551,"""O Batalhão Escolar tem hoje tem apenas 120 policiais.""","A declaração é #FATO. Veja por quê:Segundo os últimos dados divulgados pelo Instituto Brasileiro de Geografia e Estatística (IBGE), referentes a 1° de julho de 2021, e divulgados em agosto do ano passado, o Distrito Federalcresceu 1,27% em relação a 2020. Ainda de acordo com a pesquisa, este aumento significa um crescimento de39.176 moradores em um ano.",https://g1.globo.com/df/distrito-federal/eleicoes/2022/noticia/2022/09/15/veja-o-que-e-fato-ou-fake-na-entrevista-de-paulo-octavio-para-o-df1.ghtml
3549,"“Quando você coloca os dados da tuberculose, os dados da violência e os péssimos dados resultados da educação, você vai ver que esses dados negativos estão todos no mesmo território. Então quando você vai ver lá, a tuberculose é maior na Zona Oeste, a violência é maior na Zona Oeste, o número de mortes por covid-19 foi maior na Zona Oeste, a questão da educação a gente também percebe isso”. (em entrevista no Youtube, em 26/10)",#NÃOÉBEMASSIM. Veja o porquê:O Ministério Público afirma que o então prefeito Eduardo Paes pagou em dobro o benefício das gratuidades e que houve improbidade administrativa ao direcionar o edital do processo licitatório em favor das empresas de ônibus que já atuavam no ramo.,https://g1.globo.com/fato-ou-fake/noticia/2020/10/30/veja-o-que-e-fato-ou-fake-nas-declaracoes-dos-candidatos-a-prefeitura-do-rio-na-5a-semana-de-campanha.ghtml
327,"Além disso, aprimeira foto de Maduro divulgada após sua capturafoi publicada por Trump. Nela, o líder venezuelano aparece com óculos escuros, protetores de ouvido e aparentemente algemado(veja abaixo). Também veste moletom – diferentemente da imagem enganosa, na qual está com camisa branca e casaco preto.","Circula nas redes sociais uma foto supostamente mostrando o ditador deposto da Venezuela, Nicolás Maduro, acompanhado por agentes dos Estados Unidosapós ser capturado neste sábado (3).É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/01/06/e-fake-que-foto-mostre-maduro-sendo-escoltado-por-agentes-dos-eua-apos-captura-imagem-foi-criada-com-inteligencia-artificial.ghtml
3359,"""No seu programa de governo em 2016, Crivella se comprometeu a cumprir 50 propostas. Foi mentira. Das 50, ele só cumpriu uma"" (no horário eleitoral, em 25/11)","A declaração é #FATO. Veja o porquê:A aprovação teve aumento tanto nos anos iniciais quanto nos anos finais do ensino fundamental entre 2017 e2019. Entre os anos iniciais, passou de 0,93 em 2017 para 0,96 em 2019. Entre os anos finais, cresceu de 0,87 para 0,92 no mesmo período.",https://g1.globo.com/fato-ou-fake/noticia/2020/11/27/veja-o-que-e-fato-ou-fake-nas-declaracoes-dos-candidatos-a-prefeitura-do-rio-na-2a-semana-de-campanha-do-2o-turno.ghtml

In [116]:
# apply status map
# if naoebemassim in unidecode(str(next_item_text)).strip().lower() then status = 'NAOEBEMASSIM'
# elif 'fato' in next_item_text.upper() then status = 'FATO'
# elif 'fake' in next_item_text.upper() then status = 'FAKE'
# else status = 'UNKNOWN'

def determine_status(text):
    text_upper = text.upper()
    text_unidecode = unidecode(str(text)).strip().lower()
    
    if 'naoebemassim' in text_unidecode:
        return 'NAOEBEMASSIM'
    elif 'FATO' in text_upper:
        return 'FATO'
    elif 'FAKE' in text_upper:
        return 'FAKE'
    else:
        return 'UNKNOWN'
    
extracted_df['status'] = extracted_df['next_item_text'].apply(determine_status)
extracted_df[['blockquote_text', 'next_item_text', 'url', 'status']].head(50)

,blockquote_text,next_item_text,url,status
0,"O vídeo foi gravado no cemitério de Annotto Bay, na região nordeste do país. Segundo uma reportagem do jornal local ""Jamaica Observer"", os totens se tornaram uma tradição popular por lá, para auxiliar na localização dos túmulos e manter viva a memória dos falecidos. Um funcionário explicou, em entrevista, que os próprios familiares das pessoas enterradas escolhem as fotos, que depois são transformadas em grandes imagens em 2D. Para fixá-las, uma haste de aço é cimentada na sepultura.","Circula nas redes sociais um vídeo que mostra um cemitério na Jamaica repleto de totens de papelão, confeccionados em tamanho real, para representar as pessoas enterradas no local.É #FATO.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/23/e-fato-cemiterio-na-jamaica-tem-totens-com-fotos-em-tamanho-real-de-pessoas-enterradas.ghtml,FATO
1,OFato ou Fakepesquisou pelo cemitério de Annotto Bay no Google Maps e confirmou que os totens são visíveis a partir de ruas ao lado do cemitério.Veja as imagens disponíveis no Google Street View:,"Circula nas redes sociais um vídeo que mostra um cemitério na Jamaica repleto de totens de papelão, confeccionados em tamanho real, para representar as pessoas enterradas no local.É #FATO.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/23/e-fato-cemiterio-na-jamaica-tem-totens-com-fotos-em-tamanho-real-de-pessoas-enterradas.ghtml,FATO
2,"Mas isso não é verdade.OFato ou Fakeenviou o material à assessoria de imprensa do TSE, que respondeu, por e-mail:""O conteúdo é falso. Em 22 de março de 2022, o TSE arquivou consulta formulada [em 16 de fevereiro] pelaAdvocacia-Geral da União(AGU) que questionava se é possível, em ano eleitoral, a redução, a partir de lei aprovada pelo Congresso Nacional, da alíquota de impostos e contribuições sobre produtos e insumos. Por unanimidade, o Plenário decidiu não conhecer da consulta, o que significa que o julgamento não foi levado adiante para análise do mérito da questão, que envolve, entre outros pontos, a diminuição do preço dos combustíveis"".","Circula nas redes sociais uma publicação dizendo que, em 2022, oTribunal Superior Eleitoral(TSE) proibiu o governo do então presidenteJair Bolsonaro(PL) de reduzir os preços da gasolina em 2022.É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/25/e-fake-que-tse-proibiu-bolsonaro-de-baixar-preco-de-combustiveis-em-2022.ghtml,FAKE
3,"Segundo o ex-ministro do TSE Carlos Horbach, relator do caso em 2022,a consulta da AGU foi rejeitada por falta de objetividade. No voto, ele afirmou:""É inviável a formulação de consultas para análises de possíveis condutas vedadas, uma vez que sua verificação exige minuciosa análise das circunstâncias fáticas concretas. À luz do entendimento do TSE, a abstração se traduz na completa desvinculação de casos concretos, o que deve ser aliado à necessária objetividade do questionamento, sob pena do cabimento de inúmeras respostas possíveis"".","Circula nas redes sociais uma publicação dizendo que, em 2022, oTribunal Superior Eleitoral(TSE) proibiu o governo do então presidenteJair Bolsonaro(PL) de reduzir os preços da gasolina em 2022.É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/25/e-fake-que-tse-proibiu-bolsonaro-de-baixar-preco-de-combustiveis-em-2022.ghtml,FAKE
4,"Não há, no texto do ECA Digital, qualquer menção ao bloqueio de aparelhos eletrônicos ou de sistemas operacionais como um todo. É prevista, sim, a implementação de mecanismos de verificação de idade para impedir o acesso de crianças e adolescentes a aplicativos ou plataformas que apresentem conteúdo digital inadequado, mas uma possível 'barragem' não acarretaria na inutilização do aparelho usado.","Circulam nas redes sociais publicações afirmando que iPhones poderiam ser bloqueados no Brasil após a entrada em vigor da lei 15.211/2025,batizada de Estatuto da Criança e do Adolescente Digital (ECA Digital)e apelidada de “Lei Felca”, em referência ao influenciador Felipe Bressanim,que viralizou em 2025 após publicar um vídeo sobre a adultização de menores.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/25/e-fake-que-lei-felca-causara-bloqueio-de-iphones.ghtml,FAKE
5,"Os números exibidos nos posts estão incorretos. AoFato ou Fake, o gerente Edivaldo Saraiva desmentiu as alegações e apontou que uma foto real do posto foi editada para que os preços ficassem maiores: ""Alguém passou, tirou uma foto da nossa placa de preço. A pessoa adulterou, fez essa montagem"".","Circula nas redes socias uma foto que supostamente mostraria preços exorbitantes de combustíveis em um posto de gasolina de São Félix do Xingu, no Pará, após a guerra no Irã.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fake-foto-de-posto-com-litro-de-gasolina-comum-a-r-1285-e-diesel-a-r-1589-trata-se-de-montagem.ghtml,FAKE
6,"""Esclarecemos que se trata de uma montagem, que não correspondem aos preços reais praticados em nossas unidades. Infelizmente esse tipo de ato pode gerar desinformação e prejudicar a imagem de quem trabalha seriamente todos os dias"", diz o responsável pelas mídias do posto.","Circula nas redes socias uma foto que supostamente mostraria preços exorbitantes de combustíveis em um posto de gasolina de São Félix do Xingu, no Pará, após a guerra no Irã.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fake-foto-de-posto-com-litro-de-gasolina-comum-a-r-1285-e-diesel-a-r-1589-trata-se-de-montagem.ghtml,FAKE
7,"A escalada da guerra no Oriente Médio e ofechamento do Estreito de Ormuzlevaram ao aumento do preço dos combustíveis no Brasil. Entre 8 e 14 de março, o preço médio do litro do diesel nos postos do paíssubiu mais de 11%, segundo a Agência Nacional do Petróleo, Gás Natural e Biocombustíveis (ANP).Passou de R$ 6,08 para R$ 6,80.","Circula nas redes socias uma foto que supostamente mostraria preços exorbitantes de combustíveis em um posto de gasolina de São Félix do Xingu, no Pará, após a guerra no Irã.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fake-foto-de-posto-com-litro-de-gasolina-comum-a-r-1285-e-diesel-a-r-1589-trata-se-de-montagem.ghtml,FAKE
8,"OFato ou Fakesubmeteu a imagem sem tarja ao SynthID. Essa plataforma do Google verifica conteúdos criados com a ferramenta de IA da própria companhia. A tecnologiainsere uma marca d'água para identificar esse tipo de material. Embora imperceptível para humanos, o ""selo"" é detectável pelo sistema.","Circula nas redes socias uma foto que supostamente mostraria preços exorbitantes de combustíveis em um posto de gasolina de São Félix do Xingu, no Pará, após a guerra no Irã.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fake-foto-de-posto-com-litro-de-gasolina-comum-a-r-1285-e-diesel-a-r-1589-trata-se-de-montagem.ghtml,FAKE
9,"A cena é real e foi gravada em maio de 2025 em um zoológico de Xangai com espaços de interação com animais. O post foi compartilhado no Douyin (versão do TikTok usada na China), no qual há diversos registros similares. O zoológico tem registros de acidentes e denúncias maus-tratos contra animais(entenda mais abaixo).",É #FATO: Vídeo mostra canguru recebendo carinho de visitantes em zoológico na China,https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fato-video-mostra-canguru-deitado-recebendo-carinho-e-comida-de-visitantes-em-zoologico-na-china-assista.ghtml,FATO
10,"Para verificar o registro, oFato ou Fakeconsultou um perito computacional, que elaborou um relatório detalhando para apontar que não há indícios de manipulação nas cenas. Além disso, uma bióloga especialista em marsupiais explicou que a espécie é pouco ativa durante o dia, por ter hábitos crepusculares e noturnos(leia detalhes a seguir).",É #FATO: Vídeo mostra canguru recebendo carinho de visitantes em zoológico na China,https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fato-video-mostra-canguru-deitado-recebendo-carinho-e-comida-de-visitantes-em-zoologico-na-china-assista.ghtml,FATO
11,"Para verificar se o vídeo sofreu alguma adulteração ou manipulação, oFato ou Fakeenviou o material ao professor João Benedito dos Santos Junior, coordenador do Laboratório de Computação Forense, Perícia Computacional e Inteligência Cibernética da Pontifícia Universidade Católica de Minas Gerais (PUC Minas), doutor em ciência da computação pela Universidade de São Paulo (USP) e pós-doutor em computação pela Universidade de Coimbra, em Portugal.",É #FATO: Vídeo mostra canguru recebendo carinho de visitantes em zoológico na China,https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fato-video-mostra-canguru-deitado-recebendo-carinho-e-comida-de-visitantes-em-zoologico-na-china-assista.ghtml,FATO
12,"Segundo a especialista, as imagens apresentadas aparentam ser consistentes com as de um animal de zoológico. Ela afirmou também que cangurus têm hábitos crepusculares e noturnos e costumam economizar energia e evitar calor nas horas mais quentes, permanecendo na sombra: ""Por isso, durante o dia eles podem parecer pouco ativos ou 'preguiçosos'"".",É #FATO: Vídeo mostra canguru recebendo carinho de visitantes em zoológico na China,https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fato-video-mostra-canguru-deitado-recebendo-carinho-e-comida-de-visitantes-em-zoologico-na-china-assista.ghtml,FATO
13,"Ela também ressaltou que é muito improvávelque ele estivesse sendo fingido um desmaio, como alegado nas legendas das publicações virais. Cangurus aprendem com associações simples, e a forma de elaboração mencionada exigiria um nível de raciocínio bem mais complexo do que o conhecido para a espécie.",É #FATO: Vídeo mostra canguru recebendo carinho de visitantes em zoológico na China,https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fato-video-mostra-canguru-deitado-recebendo-carinho-e-comida-de-visitantes-em-zoologico-na-china-assista.ghtml,FATO
14,"""O que chamou atenção foi o comportamento do canguru: ele aparece deitado de barriga para cima, com os olhos fechados e quase sem reagir enquanto visitantes o tocam e tentam alimentá-lo. Esse tipo de passividade levou algumas pessoas a especular que o animal poderia estar sedado, embora isso não possa ser confirmado apenas a partir do vídeo.""",É #FATO: Vídeo mostra canguru recebendo carinho de visitantes em zoológico na China,https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fato-video-mostra-canguru-deitado-recebendo-carinho-e-comida-de-visitantes-em-zoologico-na-china-assista.ghtml,FATO
15,"""Esse tipo de contato pode causar estresse, alterar comportamentos naturais e até representar riscos tanto para os animais quanto para as pessoas. Muitos especialistas defendem que zoológicos e parques devem priorizar interações mais controladas, que respeitem o comportamento natural das espécies"".",É #FATO: Vídeo mostra canguru recebendo carinho de visitantes em zoológico na China,https://g1.globo.com/fato-ou-fake/noticia/2026/03/24/e-fato-video-mostra-canguru-deitado-recebendo-carinho-e-comida-de-visitantes-em-zoologico-na-china-assista.ghtml,FATO
16,"No entanto, a informação é falsa e resulta na distorção de dados reais sobre a geração de empregos no projeto. Documentos oficiais e posicionamentos enviados ao ""Globo"" pela empresa e pelo governo do estado da Bahia indicam que não há previsão de envio massivo de trabalhadores estrangeiros e que a prioridade é a contratação de mão de obra brasileira, especialmente local.","Vídeos e publicações que ganharam força nos últimos dias nas redes sociais afirmam que a instalação docomplexo industrial da BYD no município de Camaçari, na Região Metropolitana de Salvador, envolveria a chegada em massa de trabalhadores chineses ao Brasil. Segundo essas narrativas, cerca de 10 mil estrangeiros estariam sendo trazidos para ocupar empregos e formar uma espécie de ""cidade chinesa"" no local.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/19/e-fake-que-byd-contratou-10-mil-chineses-para-formar-cidade-na-bahia.ghtml,FAKE
17,"A afirmação de que 10 mil chineses serão levados para Camaçari não é verdadeira. O número citado nas publicações se refere, na realidade, à estimativa de empregos que o projeto deve gerar — majoritariamente ocupados por brasileiros. Em resposta ao ""Globo"", a BYD foi categórica: ""Não. Essa informação é falsa. A BYD não vai trazer trabalhadores chineses em grande escala para Camaçari"".","Vídeos e publicações que ganharam força nos últimos dias nas redes sociais afirmam que a instalação docomplexo industrial da BYD no município de Camaçari, na Região Metropolitana de Salvador, envolveria a chegada em massa de trabalhadores chineses ao Brasil. Segundo essas narrativas, cerca de 10 mil estrangeiros estariam sendo trazidos para ocupar empregos e formar uma espécie de ""cidade chinesa"" no local.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/19/e-fake-que-byd-contratou-10-mil-chineses-para-formar-cidade-na-bahia.ghtml,FAKE
18,"Ou seja, o número que circula nas redes foi retirado de contexto: trata-se da projeção de empregos gerados, não de trabalhadores estrangeiros.","Vídeos e publicações que ganharam força nos últimos dias nas redes sociais afirmam que a instalação docomplexo industrial da BYD no município de Camaçari, na Região Metropolitana de Salvador, envolveria a chegada em massa de trabalhadores chineses ao Brasil. Segundo essas narrativas, cerca de 10 mil estrangeiros estariam sendo trazidos para ocupar empregos e formar uma espécie de ""cidade chinesa"" no local.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/19/e-fake-que-byd-contratou-10-mil-chineses-para-formar-cidade-na-bahia.ghtml,FAKE
19,"O texto diz: ""De acordo com o professor, o estudo inicial considerou tumores de até 2,5 cm. No entanto, a conclusão final da pesquisa apontou que a crioablação apresentou 100% de eficácia em tumores de até 2 cm. Para tumores de até 2,5 cm, a eficácia observada foi de 94%. Por esse motivo, ele fez a correção desse ponto no material. O professor também realizou uma atualização geral das informações presentes na mensagem [viral] e orienta que a publicação pode ser recebida com otimismo, considerando os resultados promissores do estudo"".","Circula no WhatsApp uma mensagem afirmando que a Universidade Federal de São Paulo (Unifesp) iniciou testes com uma técnica inovadora de ""congelamento de tumores"".É #FATO.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/19/e-fato-unifesp-testa-tecnica-de-congelamento-de-tumores-contra-cancer-de-mama-inicial.ghtml,FATO
20,"As postagens são enganosas porque, apesar de a nova regulamentação ter de fato obrigado o mercado de jogos eletrônicos a implementar medidas de verificação de idade e restrição de conteúdo +18, a Rockstar jamais anunciou que deixará de comercializar seus produtos no Brasil por completo.",O que é #FATO e o que é #FAKE na guerra entre Estados Unidos e Irã no Oriente Médio,https://g1.globo.com/fato-ou-fake/noticia/2026/03/20/nao-e-bem-assim-gta-vi-nao-sera-comercializado-no-brasil-apos-implementacao-da-lei-felca.ghtml,FATO
21,"Em comunicado divulgado nesta terça, a empresa anunciou que irá parar de vender jogos para o Windows diretamente a consumidores no Brasil por meio de sua loja digital própria, mas que as obras, incluindo ""Grand theft auto VI"", previsto para ser lançado em novembro, continuarão disponíveis em mídia física e digital através de lojas eletrônicas como a PlayStation Store, a Microsoft Store e a Steam e poderão ser jogados normalmente em plataformas como PlayStation 5, Xbox Series X/S, Nintendo Switch 2 e PC.",O que é #FATO e o que é #FAKE na guerra entre Estados Unidos e Irã no Oriente Médio,https://g1.globo.com/fato-ou-fake/noticia/2026/03/20/nao-e-bem-assim-gta-vi-nao-sera-comercializado-no-brasil-apos-implementacao-da-lei-felca.ghtml,FATO
22,"Embora seja real — e não uma produção de inteligência artificial (IA), por exemplo —, o vídeo está fora de contexto. A cena foi captada depois que Bolsonaro sofreu umatentado à faca, durante a campanha presidencial de 2018. Portanto nada tem a ver com recente internação do ex-presidente (leia mais abaixo).",Circula nas redes sociais um post que exibe um vídeo do ex--presidenteJair Bolsonaro(PL) na Unidade de Terapia Intensiva (UTI) e sugere que as imagens são de uma internação recente.É#FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2026/03/20/e-fake-que-video-de-bolsonaro-deitado-em-leito-de-uti-seja-recente-imagem-foi-registrada-apos-facada-em-2018.ghtml,FAKE
23,"OFato ou Fakeentrou em contato com assessoria de imprensa da ex-primeira-dama, que respondeu com a seguinte mensagem, via WhatsApp: ""Esse vídeo é antigo. Foi tirado em 2018, no Hospital Albert Einstein, em São Paulo, após o atentado da facada contra o presidente Bolsonaro. No vídeo, a Sra. Michelle aparece com cabelo claro e mexas loiras, enquanto atualmente o cabelo dela está mais curto e escuro"".",Circula nas redes sociais um post que exibe um vídeo do ex--presidenteJair Bolsonaro(PL) na Unidade de Terapia Intensiva (UTI) e sugere que as imagens são de uma internação recente.É#FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2026/03/20/e-fake-que-video-de-bolsonaro-deitado-em-leito-de-uti-seja-recente-imagem-foi-registrada-apos-facada-em-2018.ghtml,FAKE
24,"Mas isso não é verdade. AoFato ou Fake, o senador negou ter feito feito qualquer comentário em defesa do fim do salário mínimo. Além disso, a versão impressa da ""Infomoney"" parou de circular em 2015. O material que viralizou nas redes, portanto, é uma montagem(leia detalhes abaixo).",Circula nas redes sociais um post alegando que o senador e pré-candidato à Presidência da RepúblicaFlávio Bolsonaro(PL-RJ) deu uma declaração proponto a redução ou o fim do salário mínimo.É#FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2026/03/23/e-fake-que-flavio-bolsonaro-propos-acabar-com-salario-minimo.ghtml,FAKE
25,"OFato ou Fakeentrou em contato com a assessoria de imprensa de Flávio Bolsonaro para questionar sobre a declaração atribuída a ele a respeito do fim do salário mínimo. A resposta, encaminhada por WhatsApp, afirma: ""Não existe, nunca existiu e nunca foi apresentada por mim qualquer proposta nesses termos.A primeira versão do meu plano de resgate do Brasil ainda nem foi apresentada, então é impossível falar de qualquer reforma. E o que vamos apresentar no dia 30 de março, em São Paulo, serão os pilares em algumas áreas importantes"".",Circula nas redes sociais um post alegando que o senador e pré-candidato à Presidência da RepúblicaFlávio Bolsonaro(PL-RJ) deu uma declaração proponto a redução ou o fim do salário mínimo.É#FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2026/03/23/e-fake-que-flavio-bolsonaro-propos-acabar-com-salario-minimo.ghtml,FAKE
26,"O vídeo foi gravado no cemitério de Annotto Bay, na região nordeste do país. Segundo uma reportagem do jornal local ""Jamaica Observer"", os totens se tornaram uma tradição popular por lá, para auxiliar na localização dos túmulos e manter viva a memória dos falecidos. Um funcionário explicou, em entrevista, que os próprios familiares das pessoas enterradas escolhem as fotos, que depois são transformadas em grandes imagens em 2D. Para fixá-las, uma haste de aço é cimentada na sepultura.","Circula nas redes sociais um vídeo que mostra um cemitério na Jamaica repleto de totens de papelão, confeccionados em tamanho real, para representar as pessoas enterradas no local.É #FATO.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/23/e-fato-cemiterio-na-jamaica-tem-totens-com-fotos-em-tamanho-real-de-pessoas-enterradas.ghtml,FATO

In [117]:
extracted_df['status'].value_counts()

status
FAKE            2046
FATO            1118
NAOEBEMASSIM     587
Name: count, dtype: int64

In [118]:
extracted_df[extracted_df['status'] == 'FAKE'][['blockquote_text', 'next_item_text', 'url', 'status']].sample(20)

,blockquote_text,next_item_text,url,status
625,"""Os falsos anúncios atraem os pacientes oferecendo medicamentos mais baratos e até de forma gratuita 'após a realização de cadastro'. Atenção: os anúncios são falsos. A Anvisa não comercializa qualquer medicamento ou serve de intermediária para a sua venda"", detalha o comunicado.","Circulam nas redes sociais anúncios que simulam símbolos do governo federal e levam a site que imita a página da Agência Nacional de Vigilância Sanitária (Anvisa) com a promessa de venda de Mounjaro (uma das ""canetas"" usadas no tratamento de obesidade e diabetes).É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/10/09/e-fake-site-que-imita-pagina-da-anvisa-e-promete-venda-de-mounjaro.ghtml,FAKE
494,"O resultado levou a um vídeo publicado no próprio dia da megaoperação, 28 de outubro, pelo perfil oficial de Cláudio Castro no Instagram. Na gravação, é possível ver que o governador faz os mesmos gestos visto no material falso e usa as mesmas roupas. Porém, em nenhum momento, menciona Lula ou o processo de qual é acusado. Em vez disso, faz uma atualização sobre os desdobramentos da ação policial .","Circula nas redes sociais uma publicação que mostra o governador doRio de Janeiro,Cláudio Castro(PL), dizendo que a esquerda e o presidenteLula(PT) irão cassá-lo.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/11/11/e-fake-video-de-claudio-castro-dizendo-que-lula-e-esquerda-vao-cassa-lo-cena-foi-manipulada-com-inteligencia-artificial.ghtml,FAKE
1502,"""Essa medida do Banco Central tem o objetivo de combater fraudes, uma vez que criminosos frequentemente utilizam CPFs de pessoas falecidas ou CNPJs irregulares para aplicar golpes. Portanto, ter impostos em atraso não impede ninguém de utilizar o Pix.""",Circulam nas redes sociais publicações dizendo que o governo Lula vai excluir o PIX de quem deve impostos àReceita Federal.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/03/13/e-fake-que-o-governo-vai-excluir-o-pix-de-quem-deve-imposto-a-receita-federal.ghtml,FAKE
2292,“Que rachadinha? Rachadinha ‘é seus’ filhos roubando milhões de empresas após a sua chegada no poder.”,"A declaração é #FAKE. Veja por quê:Segundo dados do Departamento Intersindical de Estatística e Estudos Socioeconômicos (Dieese) o salário mínimo em janeiro de 2003, quando Lula assumiu, era de R$ 200. No último ano de governo do petista, em 2010,o salário mínimo era de R$ 510. Considerando a inflação, o aumento real é de 54%.",https://g1.globo.com/fato-ou-fake/politica/noticia/2022/09/30/veja-o-que-e-fato-ou-fake-nas-falas-dos-presidenciaveis-no-debate-da-globo.ghtml,FAKE
791,"""O texto no documento em poder da pessoa parece incomumente claro e imposto digitalmente, especialmente na página direita. O estilo da fonte é inconsistente com o de documentos oficiais típicos"".","Circula nas redes sociais uma imagem que mostra o presidente dosEstados Unidos,Donald Trump, mostrandoa suposta carta ao bilionário Jeffrey Epstein na qual aparece o desenho de uma mulher nua.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/09/09/e-fake-foto-de-trump-mostrando-suposta-carta-a-epstein-com-desenho-de-mulher-nua-trata-se-de-montagem.ghtml,FAKE
3533,"“Quando fui governador, autorizei o uso das bicicletas nas rodovias paulistas, inclusive criando a ‘Rota Márcia Prado’, na descida da serra, que foi um sucesso” (no Twitter, em 25/10)","A declaração é #FAKE. Veja o porquê:Ao contrário do declarado pelo candidato, a atual gestão, iniciada em janeiro de 2017, requalificou, ou seja, reformou, 28,46 km de corredores de ônibus, número bem abaixo do número citado por Bruno Covas (PSDB), segundo a própria assessoria dele.",https://g1.globo.com/fato-ou-fake/noticia/2020/10/31/veja-o-que-e-fato-ou-fake-nas-declaracoes-dos-candidatos-a-prefeitura-de-sp-na-5a-semana-de-campanha.ghtml,FAKE
3097,"""Quanto eu gastei na minha campanha? Eu gastei R$ 2,5 milhões. Em 2018.""","A declaração é #FAKE. Veja por quê:A PEC do teto de gastosfoi promulgada no Congresso Nacional em dezembro de 2016, durante o governo de Michel Temer (MDB). Temer governou em 2017 e em 2018 com a lei já em vigência.",https://g1.globo.com/fato-ou-fake/eleicoes/noticia/2022/08/09/veja-o-que-e-fato-ou-fake-na-entrevista-de-jair-bolsonaro-para-o-podcast-flow.ghtml,FAKE
666,"Isso porque, embora a cena seja real – e não algo produzido por inteligência artificial (IA) –, as imagens não têm nada a ver com uma suposta ajuda humanitária indo em direção a Gaza. Trata-se, na verdade, da comemoração de torcedores do time de futebol Galatasaray, daTurquia(leia mais abaixo).",Circulam nas redes sociais posts com um vídeo que supostamente mostra um grupo de barcos com ativistas viajando com destino a Gaza.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/10/02/e-fake-que-video-de-barcos-com-pessoas-comemorando-mostre-ativistas-em-direcao-a-gaza-trata-se-da-torcida-do-galatasaray.ghtml,FAKE
2207,"""Não tem corrupção no meu governo"" (Jair Bolsonaro)","A declaração é #FAKE. Veja por quê:Ministros do governo de Jair Bolsonaro são alvos de investigações por suspeita de corrupção que estão em andamento. Em 2021, o ministro do Meio Ambiente, Ricardo Salles, foi acusado de participar de um grupo de exportação ilegal de madeira. As investigações da Polícia Federal apontaram para a existência de um ""esquema de facilitação ao contrabando de produtos florestais"", que teria o envolvimento de Salles e de gestores do ministério e do Ibama.",https://g1.globo.com/fato-ou-fake/politica/noticia/2022/10/28/corrupcao-transposicao-do-sao-francisco-e-pobreza-veja-os-temas-mais-checados-pelo-fato-ou-fake-nas-falas-de-lula-e-bolsonaro.ghtml,FAKE
720,"Trump não fez qualquer proibição como essa. OFato ou Fakeentrou em contato com a assessoria de imprensa da primeira-dama, que disse, por mensagem: ""A informação é realmente falsa. A primeira-dama não está com nenhuma restrição de circulação em NY. Inclusive tem realizado diversas agendas durante esses dias, dentro e fora da ONU"".","Circulam nas redes sociais publicações que alegam que a primeira-damaJanjada Silva foi proibida de circular em Nova York pelo presidente dosEstados Unidos,Donald Trump.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/09/24/e-fake-que-trump-proibiu-janja-de-circular-em-nova-york-em-viagem-para-reuniao-da-onu.ghtml,FAKE
370,"OFato ou Fakesubmeteu o vídeo ao SynthID Detector, ferramenta do Google que identifica conteúdo gerados com a IA da própria empresa. Resultado da análise: ""Feito com IA do Google (vídeo) – Synth ID identificado em todo ou parte do conteúdo carregado"" .","Circula nas redes sociais uma foto do presidente americano, Donald Trump, caminhando com um andador.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/12/15/e-fake-foto-de-trump-caminhando-com-andador-imagem-foi-criada-com-inteligencia-artificial.ghtml,FAKE
1538,"""O Ministério da Cultura informa que o filme 'Ainda estou aqui' não conta com recursos públicos federais. A obra é uma produção brasileira, em regime de coprodução internacional com a França e financiada com recursos próprios"".","Circulam nas redes sociais publicações que afirmam que o filme brasileiro ""Ainda estou aqui"" –indicado em três categorias no Oscar 2025– recebeu recursos da Lei Rouanet, como é conhecida a Lei de Incentivo à Cultura.É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/01/24/e-fake-que-ainda-estou-aqui-recebeu-recursos-da-lei-rouanet.ghtml,FAKE
1868,"""Nos últimos doze anos, Belo Horizonte perdeu quase metade das viagens das empresas de ônibus.""","A declaração é #FAKE. Veja por quê: Foram realizadas600.879viagens pelo transporte coletivo convencional municipal ao longo de todo o mês dejunho de 2024, de acordo com dados mais recentes da Superintendência de Mobilidade da capital. Nomesmo mês de 2012, há 12 anos, haviam sido716.299— ou seja, uma redução de16,1%.",https://g1.globo.com/fato-ou-fake/minas-gerais/noticia/2024/09/04/veja-o-que-e-fato-ou-fake-nas-entrevistas-dos-candidatos-a-prefeitura-de-bh-ao-g1.ghtml,FAKE
53,"A cena ocorreu durante a estreia do filme ""Um Novo Despertar"" no Festival de Cannes, em 17 de maio de 2011. Na ocasião, um homem caiu na escada da premiação ao ser detido por seguranças. Além disso, não há nenhum registro de que Chalamet tenha caído no tapete vermelho do Oscar deste ano.",Circula nas redes sociais uma foto que supostamente mostraria o ator Timothée Chalamet caindo na escada do tapete vermelho do Oscar neste domingo (15).É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2026/03/16/e-fake-que-timothee-chalamet-caiu-no-tapete-vermelho-do-oscar-foto-mostra-queda-de-intruso-no-festival-de-cannes-de-2011.ghtml,FAKE
529,"""Em vez disso, a regra principal é que a renda mensal da família/domicílio não pode ultrapassar R$ 218 per capita. Para se enquadrar, é necessário somar a renda total da família e dividir pelo número de membros. Um domicílio que tenha apenas uma pessoa trabalhando, com uma renda de 1 salário mínimo [R$ 1.518,00], e tenha 7 pessoas na família é elegível"", exemplifica a especialista. Nesse caso, a renda per capita seria de R$ 216,85.",Circula nas redes sociais um cartaz que compara o número de desempregados do Brasil ao de beneficiários do Bolsa Família. A mensagem sugere que esses dados são comparáveis e que o programa do governo federal seria voltado apenas a quem não tem trabalho.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/10/31/e-fake-cartaz-que-compara-numero-de-desempregados-e-de-beneficiarios-do-bolsa-familia.ghtml,FAKE
1099,"""O MME reitera que não houve qualquer venda de urânio para o Irã e que nenhuma de suas empresas vinculadas têm relações com o país, no campo da exportação de urânio, seus concentrados ou derivados. Toda a produção nacional é utilizada para atender às necessidades das usinas Angra 1 e 2, no Rio de Janeiro, operadas pela Eletronuclear.""",Circulam nas redes sociais posts sugerindo que o Brasil forneceu urânio aoIrã.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/06/18/e-fake-que-o-brasil-forneceu-uranio-ao-ira.ghtml,FAKE
1461,"""O único efeito, que é o pequeno aquecimento, não é diferente do que ocorre quando se aquece a água em um fogão"", explicou.",É #FAKE que 'água solarizada' regule hormônios e ajude na queda de cabelo,https://g1.globo.com/fato-ou-fake/noticia/2025/03/28/e-fake-que-agua-solarizada-regule-hormonios-e-ajude-na-queda-de-cabelo.ghtml,FAKE
1204,"OFato ou Faketambém enviou um e-mail à assessoria de imprensa de Leonardo, que negou a autenticidade do material: ""O vídeo em questão não foi produzido, gravado e tampouco divulgado pelo cantor. Leonardo, inclusive desconhecia a existência dele"".","Circula nas redes um vídeo do sertanejoLeonardoconvidando um de seus filhos, o também cantor Zé Felipe, a ir para uma casa de prostituição para superaro recente fim do seu casamentocomVirginia Fonseca.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/05/30/e-fake-video-de-leonardo-convidando-ze-felipe-a-sair-com-prostitutas-para-esquecer-virginia-conteudo-foi-feito-por-inteligencia-artificial.ghtml,FAKE
2024,"""O objetivo do radar não é reduzir acidentes, senão não teria tanto acidente no trânsito de São Paulo.”","A declaração é #FAKE. Veja por quê:A candidatura de Datena não firmou, até o momento, aliança com outros partidos além do PSDB e Cidadania, que estão federados e têm que disputar juntos estas eleições municipais. No entanto, há outros candidatos à Prefeitura de São Paulo que têm apoio apenas de seus próprios partidos. Um exemplo é Marina Helena, que registrou sua candidatura na Justiça Eleitoral apenas com sua legenda, o Novo. Tabata Amaral (PSB), Pablo Marçal (PRTB), Altino Prazeres, João Pimenta (PCO) e Bebetto Haddad (DC) são outros exemplos de candidatos que não ampliaram a aliança e devem ter apenas suas legendas na coligação. Os postulantes têm até o dia 15 de agosto para registrarem suas candidaturas no Tribunal Superior Eleitoral (TSE).",https://g1.globo.com/fato-ou-fake/sao-paulo/noticia/2024/08/06/veja-o-que-e-fato-ou-fake-na-entrevista-de-datena-para-o-assunto.ghtml,FAKE
182,"OFato ou Fakesubmeteu submeteu a imagem ao SynthID Detector, plataforma do Google que verifica conteúdos gerados com a ferramenta de IA da própria empresa. O resultado da análise apontou: ""Feito com IA do Google – Synth ID identificado em todo ou parte do conteúdo carregado"" (veja abaixo).","Circula nas redes sociais uma imagem que supostamente mostra um flagrante de Jeffrey Epstein (1953-2019),bilionário conhecido por sua ligação com uma vasta rede de tráfico sexual e de menores no início dos anos 2000, caminhando recentemente pelas ruas de Israel.É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/02/11/e-fake-que-foto-mostre-jeffrey-epstein-vivo-em-israel-imagem-foi-criada-com-a-ia-do-google.ghtml,FAKE

In [120]:
extracted_df[extracted_df['next_item_text'].str.contains('porque')][['blockquote_text', 'next_item_text', 'url', 'status']].sample(20)

,blockquote_text,next_item_text,url,status
368,"""Por um erro de digitação -- provocado e reconhecido documentalmente pela Funai -- a demarcação da Terra Indígena Uru-Eu-Wau-Wau acabou se sobrepondo à área do assentamento. O Marco 26, descrito no projeto da Terra Indígena, está localizado na nascente do rio Igarapé Norte-Sul; entretanto, as coordenadas da nascente foram inseridas de forma incorreta, a quilômetros de distância, invadindo a área dos produtores"".",Circula nas redes sociais a publicação dizendo que oIbamaexpulsou famílias de uma área rural em Rondônia porque o governo teria vendido as terras para a China.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/12/15/e-fake-que-video-mostre-ibama-expulsando-familias-de-suas-terras-e-que-territorio-tenha-sido-vendido-para-a-china.ghtml,FAKE
3271,"""Em 7 de janeiro, o governo federal contratou 46 milhões de doses de vacinas do Butantan e, em fevereiro, mais 54 milhões de doses, além de 10 milhões de doses da União Química e 20 milhões da Precisa Medicamentos, com previsão de mais 30 milhões de doses do Butantan. Em março de 2021, mais 100 milhões de doses da Pfizer e 38 milhões de doses da Janssen”","A declaração é #FAKE. Veja o porquê:Houve, sim, uma pausa nas negociações com o instituto para a aquisição da Coronavac. Em outubro, o então ministro Eduardo Pazuello anunciou um protocolo de intenção de compra de 46 milhões de doses do imunizante, produzido pelo Instituto Butantan em parceria com a Sinovac. Um dia depois, Bolsonaro afirmou que o governo federal não ia adquirir ""vacina da China"":""Ele [Pazuello] tem um protocolo de intenções, já mandei cancelar se ele assinou. Já mandei cancelar. O presidente sou eu, não abro mão da minha autoridade. Até porque estaria comprando uma vacina que ninguém está interessado por ela, a não ser nós"".",https://g1.globo.com/fato-ou-fake/noticia/2021/06/09/veja-o-que-e-fato-ou-fake-nas-declaracoes-do-ex-secretario-elcio-franco-na-cpi-da-covid.ghtml,FAKE
366,"E prossegue: ""A desintrusão atende decisão do Supremo Tribunal Federal, no âmbito daADPF 709e tem como missão preservar a sustentabilidade, integridade e cultura dos povos indígenas, além de garantir a integridade do território e a proteção do meio ambiente da região"".",Circula nas redes sociais a publicação dizendo que oIbamaexpulsou famílias de uma área rural em Rondônia porque o governo teria vendido as terras para a China.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/12/15/e-fake-que-video-mostre-ibama-expulsando-familias-de-suas-terras-e-que-territorio-tenha-sido-vendido-para-a-china.ghtml,FAKE
637,"OFato ou Fakemostrou a publicação ao professor Thiago Carita Correra, do Departamento de Química Fundamental do Instituto de Química da Universidade de São Paulo (USP). Ele afirma: ""Não é verdade. O metanol não causa alteração de cor. Não existe teste para metanol que possa ser feito pelo consumidor. Apenas em laboratório""(leia detalhes abaixo).","Circula nas redes sociais o vídeo de um ""teste caseiro"" para, supostamente, detectar se uma bebida alcoólica tem metanol. A cena mostra uma pessoa despejando um líquido em uma fatia de pão de forma, e a descrição diz que ""se fica preto, é porque tem [a] substância"".É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/10/10/e-fake-que-teste-com-pao-detecta-se-ha-metanol-na-bebida-alcoolica.ghtml,FAKE
367,"""A destruição das estruturas ocorreu após conferência dos bancos de dados, análise de imagens e checagem dos marcos geográficos in loco que confirmaram que a região está dentro dos limites da TI. Os ocupantes das duas fazendas não possuíam qualquer documentação válida ou legal de posse da área. Não há no local Programas de Assentamentos do Incra ou qualquer outro tipo de política de distribuição de terras"".",Circula nas redes sociais a publicação dizendo que oIbamaexpulsou famílias de uma área rural em Rondônia porque o governo teria vendido as terras para a China.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/12/15/e-fake-que-video-mostre-ibama-expulsando-familias-de-suas-terras-e-que-territorio-tenha-sido-vendido-para-a-china.ghtml,FAKE
365,"AoFato ou Fake,o Instituto Nacional de Colonização e Reforma Agrária (Incra), responsável por regulamentar cadastros de imóveis rurais, diz: ""A informação de que terras estariam sendo vendidas para a China não procede. O que se mostra na região é um processo de desintrusão da Terra Indígena Uru-Eu-Wau-Wau"".",Circula nas redes sociais a publicação dizendo que oIbamaexpulsou famílias de uma área rural em Rondônia porque o governo teria vendido as terras para a China.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/12/15/e-fake-que-video-mostre-ibama-expulsando-familias-de-suas-terras-e-que-territorio-tenha-sido-vendido-para-a-china.ghtml,FAKE
638,"O professor Jorge A. W. Gut, do Centro de Pesquisa em Alimentos (FoRC), da mesma universidade, confirma: ""Não há teste caseiro para detectar a presença do metanol na bebida falsificada"".","Circula nas redes sociais o vídeo de um ""teste caseiro"" para, supostamente, detectar se uma bebida alcoólica tem metanol. A cena mostra uma pessoa despejando um líquido em uma fatia de pão de forma, e a descrição diz que ""se fica preto, é porque tem [a] substância"".É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/10/10/e-fake-que-teste-com-pao-detecta-se-ha-metanol-na-bebida-alcoolica.ghtml,FAKE
3268,"“A intenção de receber esses medicamentos [hidroxicloroquina doada pelos Estados Unidos], como eu coloquei anteriormente, foi para atendimento dos programas que o ministério conduz, como tratamento anti-malária, como lúpus e artrite reumatoide""","A declaração é #FAKE. Veja o porquê:Houve, sim, uma pausa nas negociações com o instituto para a aquisição da Coronavac. Em outubro, o então ministro Eduardo Pazuello anunciou um protocolo de intenção de compra de 46 milhões de doses do imunizante, produzido pelo Instituto Butantan em parceria com a Sinovac. Um dia depois, Bolsonaro afirmou que o governo federal não ia adquirir ""vacina da China"":""Ele [Pazuello] tem um protocolo de intenções, já mandei cancelar se ele assinou. Já mandei cancelar. O presidente sou eu, não abro mão da minha autoridade. Até porque estaria comprando uma vacina que ninguém está interessado por ela, a não ser nós"".",https://g1.globo.com/fato-ou-fake/noticia/2021/06/09/veja-o-que-e-fato-ou-fake-nas-declaracoes-do-ex-secretario-elcio-franco-na-cpi-da-covid.ghtml,FAKE
3219,"""O Ministério da Ciência e Tecnologia tem 1% do orçamento do país""","A declaração é #FAKE. Veja por quê:O déficit primário são as receitas do governo menos os gastos em um determinado período, excluindo o gastos com juros. Em 2021, de janeiro a agosto (último dado disponível), esse déficit era de R$ 83 bilhões.A estimativa é que esse valor fique em R$ 139 bilhões no fechado do ano. Considerando os 12 meses até agosto - e incorporando os juros (o que é conhecido como resultado nominal) -, esse valor é de R$ 466 bilhões. Isso porque os gastos foram elevados em 2020, por conta do auxílio emergencial. Ainda assim, os valores são muito distantes do informado pelo pré-candidato.",https://g1.globo.com/fato-ou-fake/noticia/2021/10/19/veja-o-que-e-fato-ou-fake-nas-falas-dos-pre-candidatos-do-psdb-a-presidencia-no-debate-dos-jornais-o-globo-e-valor.ghtml,FAKE
876,"De fato, aviões cargueiros da Força Aérea americana chegaram ao Brasil no final de julho para o Exercício Operacional o Tápio (EXOP Tápio). Registros oficiais no site da FAB comprovam que a colaboração ocorre desde 2018 e não tem relação com os episódios recentes envolvendo Lula e Trump. Além disso, não há registros de ""rompimento"" das Forças Armadas brasileiras com o governo petista.","Circula nas redes sociais uma publicação dizendo que as Forças Armadas brasileiras romperam com o governoLula(PT), porque participaram de um exercício com os Estados Unidos.É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/08/16/e-fake-que-chegada-de-avioes-militares-americanos-ao-brasil-signifique-rompimento-das-forcas-armadas-com-governo-lula.ghtml,FAKE
3223,"""São Paulo é o estado que mais vacina no Brasil. Que mais vacinou com a primeira dose: 99,2%""","A declaração é #FAKE. Veja por quê:O déficit primário são as receitas do governo menos os gastos em um determinado período, excluindo o gastos com juros. Em 2021, de janeiro a agosto (último dado disponível), esse déficit era de R$ 83 bilhões.A estimativa é que esse valor fique em R$ 139 bilhões no fechado do ano. Considerando os 12 meses até agosto - e incorporando os juros (o que é conhecido como resultado nominal) -, esse valor é de R$ 466 bilhões. Isso porque os gastos foram elevados em 2020, por conta do auxílio emergencial. Ainda assim, os valores são muito distantes do informado pelo pré-candidato.",https://g1.globo.com/fato-ou-fake/noticia/2021/10/19/veja-o-que-e-fato-ou-fake-nas-falas-dos-pre-candidatos-do-psdb-a-presidencia-no-debate-dos-jornais-o-globo-e-valor.ghtml,FAKE
364,"Embora as cenas mostradas no vídeo sejam reais,elas não mostram uma desapropriação de terras rurais para a venda dos terrenos à China e nem uma ação do Ibama.Na verdade, exibem uma operação feita por autoridades federais para a expulsão de produtores rurais de uma Terra Indígena em Alvorada d’Oeste, no interior de Rondônia.",Circula nas redes sociais a publicação dizendo que oIbamaexpulsou famílias de uma área rural em Rondônia porque o governo teria vendido as terras para a China.É #FAKE.,https://g1.globo.com/fato-ou-fake/noticia/2025/12/15/e-fake-que-video-mostre-ibama-expulsando-familias-de-suas-terras-e-que-territorio-tenha-sido-vendido-para-a-china.ghtml,FAKE
875,"Mas esse exercício, na verdade, é uma colaboração que ocorre desde 2018, como informa o site daForça Aérea Brasileira(FAB). O objetivo é integrar militares do Brasil e de países convidados em simulações de guerra irregular, guerra eletrônica, missões de paz e ações humanitárias. Neste ano,ele começou em 31 de julhoe tinha previsão de terminar neste sábado (16) –leia detalhes abaixo.","Circula nas redes sociais uma publicação dizendo que as Forças Armadas brasileiras romperam com o governoLula(PT), porque participaram de um exercício com os Estados Unidos.É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2025/08/16/e-fake-que-chegada-de-avioes-militares-americanos-ao-brasil-signifique-rompimento-das-forcas-armadas-com-governo-lula.ghtml,FAKE
3222,"""Fiz a única declaração de voto (em Bolsonaro) no vídeo que apresentei à sociedade gaúcha marcando muito bem quais eram as minhas diferenças""","A declaração é #FAKE. Veja por quê:O déficit primário são as receitas do governo menos os gastos em um determinado período, excluindo o gastos com juros. Em 2021, de janeiro a agosto (último dado disponível), esse déficit era de R$ 83 bilhões.A estimativa é que esse valor fique em R$ 139 bilhões no fechado do ano. Considerando os 12 meses até agosto - e incorporando os juros (o que é conhecido como resultado nominal) -, esse valor é de R$ 466 bilhões. Isso porque os gastos foram elevados em 2020, por conta do auxílio emergencial. Ainda assim, os valores são muito distantes do informado pelo pré-candidato.",https://g1.globo.com/fato-ou-fake/noticia/2021/10/19/veja-o-que-e-fato-ou-fake-nas-falas-dos-pre-candidatos-do-psdb-a-presidencia-no-debate-dos-jornais-o-globo-e-valor.ghtml,FAKE
3225,"""O único estado que fez reforma administrativa, não ajustes, foi o governo do estado de São Paulo""","A declaração é #FAKE. Veja por quê:O déficit primário são as receitas do governo menos os gastos em um determinado período, excluindo o gastos com juros. Em 2021, de janeiro a agosto (último dado disponível), esse déficit era de R$ 83 bilhões.A estimativa é que esse valor fique em R$ 139 bilhões no fechado do ano. Considerando os 12 meses até agosto - e incorporando os juros (o que é conhecido como resultado nominal) -, esse valor é de R$ 466 bilhões. Isso porque os gastos foram elevados em 2020, por conta do auxílio emergencial. Ainda assim, os valores são muito distantes do informado pelo pré-candidato.",https://g1.globo.com/fato-ou-fake/noticia/2021/10/19/veja-o-que-e-fato-ou-fake-nas-falas-dos-pre-candidatos-do-psdb-a-presidencia-no-debate-dos-jornais-o-globo-e-valor.ghtml,FAKE
3270,"“Com relação ao tratamento precoce, não era orientação do ministério”","A declaração é #FAKE. Veja o porquê:Houve, sim, uma pausa nas negociações com o instituto para a aquisição da Coronavac. Em outubro, o então ministro Eduardo Pazuello anunciou um protocolo de intenção de compra de 46 milhões de doses do imunizante, produzido pelo Instituto Butantan em parceria com a Sinovac. Um dia depois, Bolsonaro afirmou que o governo federal não ia adquirir ""vacina da China"":""Ele [Pazuello] tem um protocolo de intenções, já mandei cancelar se ele assinou. Já mandei cancelar. O presidente sou eu, não abro mão da minha autoridade. Até porque estaria comprando uma vacina que ninguém está interessado por ela, a não ser nós"".",https://g1.globo.com/fato-ou-fake/noticia/2021/06/09/veja-o-que-e-fato-ou-fake-nas-declaracoes-do-ex-secretario-elcio-franco-na-cpi-da-covid.ghtml,FAKE
3218,“Temos (...) um ICMBio militarizado”,"A declaração é #FAKE. Veja por quê:O déficit primário são as receitas do governo menos os gastos em um determinado período, excluindo o gastos com juros. Em 2021, de janeiro a agosto (último dado disponível), esse déficit era de R$ 83 bilhões.A estimativa é que esse valor fique em R$ 139 bilhões no fechado do ano. Considerando os 12 meses até agosto - e incorporando os juros (o que é conhecido como resultado nominal) -, esse valor é de R$ 466 bilhões. Isso porque os gastos foram elevados em 2020, por conta do auxílio emergencial. Ainda assim, os valores são muito distantes do informado pelo pré-candidato.",https://g1.globo.com/fato-ou-fake/noticia/2021/10/19/veja-o-que-e-fato-ou-fake-nas-falas-dos-pre-candidatos-do-psdb-a-presidencia-no-debate-dos-jornais-o-globo-e-valor.ghtml,FAKE
3220,"""Recebo o apoio não só de Aécio Neves, recebo de todo o diretório de Minas Gerais que, por unanimidade, da qual faz parte o deputado Aécio Neves, aprovou o apoio""","A declaração é #FAKE. Veja por quê:O déficit primário são as receitas do governo menos os gastos em um determinado período, excluindo o gastos com juros. Em 2021, de janeiro a agosto (último dado disponível), esse déficit era de R$ 83 bilhões.A estimativa é que esse valor fique em R$ 139 bilhões no fechado do ano. Considerando os 12 meses até agosto - e incorporando os juros (o que é conhecido como resultado nominal) -, esse valor é de R$ 466 bilhões. Isso porque os gastos foram elevados em 2020, por conta do auxílio emergencial. Ainda assim, os valores são muito distantes do informado pelo pré-candidato.",https://g1.globo.com/fato-ou-fake/noticia/2021/10/19/veja-o-que-e-fato-ou-fake-nas-falas-dos-pre-candidatos-do-psdb-a-presidencia-no-debate-dos-jornais-o-globo-e-valor.ghtml,FAKE
3269,"“[Com a decisão do STF] não há a possibilidade de o Ministério da Saúde interferir na execução das ações de atenção à saúde sem usurpar da competência e autonomia dos entes federados""","A declaração é #FAKE. Veja o porquê:Houve, sim, uma pausa nas negociações com o instituto para a aquisição da Coronavac. Em outubro, o então ministro Eduardo Pazuello anunciou um protocolo de intenção de compra de 46 milhões de doses do imunizante, produzido pelo Instituto Butantan em parceria com a Sinovac. Um dia depois, Bolsonaro afirmou que o governo federal não ia adquirir ""vacina da China"":""Ele [Pazuello] tem um protocolo de intenções, já mandei cancelar se ele assinou. Já mandei cancelar. O presidente sou eu, não abro mão da minha autoridade. Até porque estaria comprando uma vacina que ninguém está interessado por ela, a não ser nós"".",https://g1.globo.com/fato-ou-fake/noticia/2021/06/09/veja-o-que-e-fato-ou-fake-nas-declaracoes-do-ex-secretario-elcio-franco-na-cpi-da-covid.ghtml,FAKE
3266,"""As tratativas [com o Butantan] não pararam""","A declaração é #FAKE. Veja o porquê:Houve, sim, uma pausa nas negociações com o instituto para a aquisição da Coronavac. Em outubro, o então ministro Eduardo Pazuello anunciou um protocolo de intenção de compra de 46 milhões de doses do imunizante, produzido pelo Instituto Butantan em parceria com a Sinovac. Um dia depois, Bolsonaro afirmou que o governo federal não ia adquirir ""vacina da China"":""Ele [Pazuello] tem um protocolo de intenções, já mandei cancelar se ele assinou. Já mandei cancelar. O presidente sou eu, não abro mão da minha autoridade. Até porque estaria comprando uma vacina que ninguém está interessado por ela, a não ser nós"".",https://g1.globo.com/fato-ou-fake/noticia/2021/06/09/veja-o-que-e-fato-ou-fake-nas-declaracoes-do-ex-secretario-elcio-franco-na-cpi-da-covid.ghtml,FAKE

In [121]:
final_df = extracted_df[['blockquote_text', 'next_item_text', 'url', 'status']].copy()

final_df.head()

,blockquote_text,next_item_text,url,status
0,"O vídeo foi gravado no cemitério de Annotto Bay, na região nordeste do país. Segundo uma reportagem do jornal local ""Jamaica Observer"", os totens se tornaram uma tradição popular por lá, para auxiliar na localização dos túmulos e manter viva a memória dos falecidos. Um funcionário explicou, em entrevista, que os próprios familiares das pessoas enterradas escolhem as fotos, que depois são transformadas em grandes imagens em 2D. Para fixá-las, uma haste de aço é cimentada na sepultura.","Circula nas redes sociais um vídeo que mostra um cemitério na Jamaica repleto de totens de papelão, confeccionados em tamanho real, para representar as pessoas enterradas no local.É #FATO.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/23/e-fato-cemiterio-na-jamaica-tem-totens-com-fotos-em-tamanho-real-de-pessoas-enterradas.ghtml,FATO
1,OFato ou Fakepesquisou pelo cemitério de Annotto Bay no Google Maps e confirmou que os totens são visíveis a partir de ruas ao lado do cemitério.Veja as imagens disponíveis no Google Street View:,"Circula nas redes sociais um vídeo que mostra um cemitério na Jamaica repleto de totens de papelão, confeccionados em tamanho real, para representar as pessoas enterradas no local.É #FATO.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/23/e-fato-cemiterio-na-jamaica-tem-totens-com-fotos-em-tamanho-real-de-pessoas-enterradas.ghtml,FATO
2,"Mas isso não é verdade.OFato ou Fakeenviou o material à assessoria de imprensa do TSE, que respondeu, por e-mail:""O conteúdo é falso. Em 22 de março de 2022, o TSE arquivou consulta formulada [em 16 de fevereiro] pelaAdvocacia-Geral da União(AGU) que questionava se é possível, em ano eleitoral, a redução, a partir de lei aprovada pelo Congresso Nacional, da alíquota de impostos e contribuições sobre produtos e insumos. Por unanimidade, o Plenário decidiu não conhecer da consulta, o que significa que o julgamento não foi levado adiante para análise do mérito da questão, que envolve, entre outros pontos, a diminuição do preço dos combustíveis"".","Circula nas redes sociais uma publicação dizendo que, em 2022, oTribunal Superior Eleitoral(TSE) proibiu o governo do então presidenteJair Bolsonaro(PL) de reduzir os preços da gasolina em 2022.É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/25/e-fake-que-tse-proibiu-bolsonaro-de-baixar-preco-de-combustiveis-em-2022.ghtml,FAKE
3,"Segundo o ex-ministro do TSE Carlos Horbach, relator do caso em 2022,a consulta da AGU foi rejeitada por falta de objetividade. No voto, ele afirmou:""É inviável a formulação de consultas para análises de possíveis condutas vedadas, uma vez que sua verificação exige minuciosa análise das circunstâncias fáticas concretas. À luz do entendimento do TSE, a abstração se traduz na completa desvinculação de casos concretos, o que deve ser aliado à necessária objetividade do questionamento, sob pena do cabimento de inúmeras respostas possíveis"".","Circula nas redes sociais uma publicação dizendo que, em 2022, oTribunal Superior Eleitoral(TSE) proibiu o governo do então presidenteJair Bolsonaro(PL) de reduzir os preços da gasolina em 2022.É#FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/25/e-fake-que-tse-proibiu-bolsonaro-de-baixar-preco-de-combustiveis-em-2022.ghtml,FAKE
4,"Não há, no texto do ECA Digital, qualquer menção ao bloqueio de aparelhos eletrônicos ou de sistemas operacionais como um todo. É prevista, sim, a implementação de mecanismos de verificação de idade para impedir o acesso de crianças e adolescentes a aplicativos ou plataformas que apresentem conteúdo digital inadequado, mas uma possível 'barragem' não acarretaria na inutilização do aparelho usado.","Circulam nas redes sociais publicações afirmando que iPhones poderiam ser bloqueados no Brasil após a entrada em vigor da lei 15.211/2025,batizada de Estatuto da Criança e do Adolescente Digital (ECA Digital)e apelidada de “Lei Felca”, em referência ao influenciador Felipe Bressanim,que viralizou em 2025 após publicar um vídeo sobre a adultização de menores.É #FAKE.",https://g1.globo.com/fato-ou-fake/noticia/2026/03/25/e-fake-que-lei-felca-causara-bloqueio-de-iphones.ghtml,FAKE

In [123]:
save = True

if save:
    final_df.to_csv('out/20260326_g1_extracted_blockquotes_reasonings.csv', index=False, sep='|')